//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ID_Request_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRUser
    {
        public int HRUserId { get; set; }
        public string HrUserName { get; set; }
        public string HrPassword { get; set; }
        public string LoginErrorMessage { get; set; }
        public string Section { get; set; }
    }
}
