//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ID_Request_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_Data
    {
        public int ReqId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestBy { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeId { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Section { get; set; }
        public string Issue_Status { get; set; }
    }
}
