//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ID_Request_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public string User_ID { get; set; }
        public string User_Name { get; set; }
        public string Section { get; set; }
        public string Department { get; set; }
    }
}
